swagger: "2.0"
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: javascript:alert(document.domain)//
    tokenUrl: javascript:alert(document.domain)//
    scopes:
      read: Grants read access
      write: Grants write access
      admin: Grants read and write access to administrative information
info:
  version: "2.0"
  title: XSS Authorize test
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="<a href=j&#97v&#97script:&#97lert('xss')>ClickMe</a>"></form>
paths:
  /:
    get:
      responses:
        200:
          description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="<a href=j&#97v&#97script:&#97lert('xss')>ClickMe</a>"></form>
